# src/writer.py
import sys
import os
from .schemas import UnboundServerSettings


class ConfigurationWriter:
    """
    Writes the compiled dataset to Unbound configuration files.

    Separates adblock entries (no resource records) from local authority
    entries (have resource records) so they can be written to distinct
    include files.

    finalized_data is a list of (domain, policy, records, source_url) tuples
    as returned by ReversedDomainTrie.serialize_pruned_tree().
    """

    _SKIP_IN_GENERIC_RENDER = {
        "port",
        "num_threads",
        "interface",
        "do_ip4",
        "do_ip6",
        "access_control",
    }

    def __init__(self, server_settings: UnboundServerSettings, finalized_data: list):
        self.settings = server_settings
        self.adblock_data = [item for item in finalized_data if not item[2]]
        self.local_data = [item for item in finalized_data if item[2]]

    @staticmethod
    def _to_unbound_key(python_name: str) -> str:
        return python_name.replace("_", "-")

    @staticmethod
    def _to_unbound_value(value) -> str:
        if isinstance(value, bool):
            return "yes" if value else "no"
        return str(value)

    def write_master_unbound_conf(self, output_dir: str) -> None:
        filepath = os.path.join(output_dir, "unbound.conf")
        print(f"Writing: {filepath}")

        s = self.settings

        try:
            with open(filepath, "w") as f:
                f.write("# Generated by adlist_generator. Do not edit manually.\n\n")
                f.write("server:\n")

                f.write(f"  port: {s.port}\n")
                for iface in s.interface:
                    f.write(f"  interface: {iface}\n")
                f.write(f"  do-ip4: {self._to_unbound_value(s.do_ip4)}\n")
                f.write(f"  do-ip6: {self._to_unbound_value(s.do_ip6)}\n")
                for entry in s.access_control:
                    f.write(f"  access-control: {entry.subnet} {entry.action}\n")

                f.write(f"\n  num-threads: {s.num_threads}\n")
                f.write(f"  msg-cache-size: {s.msg_cache_size}\n")
                f.write(f"  rrset-cache-size: {s.rrset_cache_size}\n")

                f.write("\n")
                rendered = self.settings.model_dump(
                    exclude=self._SKIP_IN_GENERIC_RENDER
                )
                for python_key, value in rendered.items():
                    key = self._to_unbound_key(python_key)
                    val = self._to_unbound_value(value)
                    f.write(f"  {key}: {val}\n")

                if self.local_data:
                    f.write('\n  include: "/etc/unbound/local_records.conf"\n')
                if self.adblock_data:
                    f.write('  include: "/etc/unbound/adblock.conf"\n')

        except IOError as e:
            print(f"Error writing {filepath}: {e}", file=sys.stderr)

    def _write_policy_block(self, filepath: str, title: str, dataset: list) -> None:
        try:
            with open(filepath, "w") as f:
                f.write(
                    f"# {title} — generated by adlist_generator. Do not edit manually.\n\n"
                )
                for domain, policy, records, _source in dataset:
                    f.write(f'local-zone: "{domain}" {policy}\n')
                    if records:
                        for rec_type, value in records.items():
                            f.write(f'local-data: "{domain}. IN {rec_type} {value}"\n')
        except IOError as e:
            print(f"Error writing {filepath}: {e}", file=sys.stderr)

    def write_compiled_adblock_conf(self, filepath: str) -> None:
        print(f"Writing: {filepath}")
        self._write_policy_block(filepath, "Adblock zones", self.adblock_data)

    def write_local_records_conf(self, filepath: str) -> None:
        print(f"Writing: {filepath}")
        self._write_policy_block(filepath, "Local authority records", self.local_data)

    def write_git_manifest(self, filepath: str) -> None:
        """
        Write a reversed-label audit log with source attribution.

        Format per line:
          com.example.ads -> always_nxdomain [firebog/AdguardDNS.txt]

        Reversed-label ordering groups entries by TLD and SLD, making diffs
        easier to read — related domains appear together rather than scattered
        alphabetically by subdomain.
        """
        print(f"Writing: {filepath}")
        try:
            with open(filepath, "w") as f:
                all_data = self.local_data + self.adblock_data
                for domain, policy, records, source in all_data:
                    tokens = domain.split(".")
                    tokens.reverse()
                    reversed_notation = ".".join(tokens)

                    # Derive a short source label for readability.
                    if source == "local":
                        source_label = "local"
                    else:
                        parts = source.rstrip("/").split("/")
                        source_label = (
                            "/".join(parts[-2:]) if len(parts) >= 2 else source
                        )

                    if records:
                        record_str = " ".join(f"{k}={v}" for k, v in records.items())
                        f.write(
                            f"{reversed_notation} -> {policy} [{source_label}] {{{record_str}}}\n"
                        )
                    else:
                        f.write(f"{reversed_notation} -> {policy} [{source_label}]\n")

        except IOError as e:
            print(f"Error writing {filepath}: {e}", file=sys.stderr)
