# src/writer.py
import sys
import os
from .schemas import UnboundServerSettings


class ConfigurationWriter:
    """
    Writes the compiled dataset to Unbound configuration files.

    Separates adblock entries (no resource records) from local authority
    entries (have resource records) so they can be written to distinct
    include files.

    finalized_data is a list of (domain, policy, records, source_url) tuples
    as returned by ReversedDomainTrie.serialize_pruned_tree().
    """

    # Fields handled by explicit rendering logic rather than the generic loop.
    # These are either repeated keys, compound values, or need ordering control.
    _SKIP_IN_GENERIC_RENDER = {
        "port",
        "interface",
        "do_ip4",
        "do_ip6",
        "access_control",
        "domain_insecure",
        "username",
        "chroot",
        "do_daemonize",
        "pidfile",
        "logfile",
        "num_threads",
        "msg_cache_size",
        "rrset_cache_size",
        "trust_anchor_file",
        "root_hints",
        "so_sndbuf",
        "so_rcvbuf",
    }

    def __init__(self, server_settings: UnboundServerSettings, finalized_data: list):
        self.settings = server_settings
        self.adblock_data = [item for item in finalized_data if not item[2]]
        self.local_data = [item for item in finalized_data if item[2]]

    @staticmethod
    def _to_unbound_key(python_name: str) -> str:
        """Convert a Python underscore field name to an Unbound hyphenated directive."""
        return python_name.replace("_", "-")

    @staticmethod
    def _to_unbound_value(value) -> str:
        """Render a Python value as an Unbound config value string."""
        if isinstance(value, bool):
            return "yes" if value else "no"
        return str(value)

    def write_master_unbound_conf(self, output_dir: str) -> None:
        """
        Write unbound.conf.

        Directives are grouped by concern to match conventional unbound.conf
        layout. Repeated-key directives (interface, access-control,
        domain-insecure) are handled explicitly. All remaining scalar fields
        are rendered generically so new schema additions appear automatically.
        """
        filepath = os.path.join(output_dir, "unbound.conf")
        print(f"Writing: {filepath}")

        s = self.settings

        try:
            with open(filepath, "w") as f:
                f.write("# Generated by adlist_generator. Do not edit manually.\n\n")
                f.write("server:\n")

                # --- Network ---
                for iface in s.interface:
                    f.write(f"  interface: {iface}\n")
                f.write(f"  port: {s.port}\n")
                f.write(f"  do-ip4: {self._to_unbound_value(s.do_ip4)}\n")
                f.write(f"  do-ip6: {self._to_unbound_value(s.do_ip6)}\n")
                f.write(f"  so-sndbuf: {s.so_sndbuf}\n")
                f.write(f"  so-rcvbuf: {s.so_rcvbuf}\n")

                # --- Process / runtime ---
                f.write(f'\n  username: "{s.username}"\n')
                f.write(f'  chroot: "{s.chroot}"\n')
                f.write(f"  do-daemonize: {self._to_unbound_value(s.do_daemonize)}\n")
                f.write(f'  pidfile: "{s.pidfile}"\n')
                f.write(f'  logfile: "{s.logfile}"\n')

                # --- Threading and cache ---
                f.write(f"\n  num-threads: {s.num_threads}\n")
                f.write(f"  msg-cache-size: {s.msg_cache_size}\n")
                f.write(f"  rrset-cache-size: {s.rrset_cache_size}\n")

                # --- Remaining scalar fields (TTL, prefetch, privacy, hardening, logging) ---
                # Rendered generically so new schema fields appear without touching the writer.
                f.write("\n")
                rendered = s.model_dump(exclude=self._SKIP_IN_GENERIC_RENDER)
                for python_key, value in rendered.items():
                    key = self._to_unbound_key(python_key)
                    val = self._to_unbound_value(value)
                    f.write(f"  {key}: {val}\n")

                # --- Access control (repeated key) ---
                if s.access_control:
                    f.write("\n")
                    for entry in s.access_control:
                        f.write(f"  access-control: {entry.subnet} {entry.action}\n")

                # --- DNSSEC ---
                f.write("\n")
                if s.trust_anchor_file:
                    f.write(f'  trust-anchor-file: "{s.trust_anchor_file}"\n')
                if s.root_hints:
                    f.write(f'  root-hints: "{s.root_hints}"\n')
                for domain in s.domain_insecure:
                    f.write(f'  domain-insecure: "{domain}"\n')

                # --- Conditional includes ---
                if self.local_data:
                    f.write('\n  include: "/etc/unbound/local_records.conf"\n')
                if self.adblock_data:
                    f.write('  include: "/etc/unbound/adblock.conf"\n')

        except IOError as e:
            print(f"Error writing {filepath}: {e}", file=sys.stderr)

    def _write_policy_block(self, filepath: str, title: str, dataset: list) -> None:
        try:
            with open(filepath, "w") as f:
                f.write(
                    f"# {title} — generated by adlist_generator. Do not edit manually.\n\n"
                )
                for domain, policy, records, _source in dataset:
                    f.write(f'local-zone: "{domain}" {policy}\n')
                    if records:
                        for rec_type, value in records.items():
                            f.write(f'local-data: "{domain}. IN {rec_type} {value}"\n')
        except IOError as e:
            print(f"Error writing {filepath}: {e}", file=sys.stderr)

    def write_compiled_adblock_conf(self, filepath: str) -> None:
        print(f"Writing: {filepath}")
        self._write_policy_block(filepath, "Adblock zones", self.adblock_data)

    def write_local_records_conf(self, filepath: str) -> None:
        print(f"Writing: {filepath}")
        self._write_policy_block(filepath, "Local authority records", self.local_data)

    def write_git_manifest(self, filepath: str) -> None:
        """Write a reversed-label audit log with source attribution."""
        print(f"Writing: {filepath}")
        try:
            with open(filepath, "w") as f:
                all_data = self.local_data + self.adblock_data
                for domain, policy, records, source in all_data:
                    tokens = domain.split(".")
                    tokens.reverse()
                    reversed_notation = ".".join(tokens)

                    if source == "local":
                        source_label = "local"
                    else:
                        parts = source.rstrip("/").split("/")
                        source_label = (
                            "/".join(parts[-2:]) if len(parts) >= 2 else source
                        )

                    if records:
                        record_str = " ".join(f"{k}={v}" for k, v in records.items())
                        f.write(
                            f"{reversed_notation} -> {policy} [{source_label}] {{{record_str}}}\n"
                        )
                    else:
                        f.write(f"{reversed_notation} -> {policy} [{source_label}]\n")

        except IOError as e:
            print(f"Error writing {filepath}: {e}", file=sys.stderr)
